name             'gina-gisshare_server'
maintainer       'UAF'
maintainer_email 'support+chef@gina.alaska.edu'
license          'apache2'
description      'Installs/Configures gina-gisshare_server'
long_description 'Installs/Configures gina-gisshare_server'
version          '0.3.5'
depends          'nfs','~> 2.0.0'
depends          'iptables-ng','~> 2.2.5'
#depends          'samba','~> 0.12.0'
depends          'apt','~> 2.7.0'
