name             'gina-gisshare_server'
maintainer       'UAF'
maintainer_email 'support+chef@gina.alaska.edu'
license          'apache2'
description      'Installs/Configures gina-gisshare_server'
long_description 'Installs/Configures gina-gisshare_server'
version          '0.1.2'
depends          'nfs','~> 2.0.0'
#depends          'samba','~> 0.12.0'
